### PR TITLE
chore: create `docs` folder under the root folder

### PR DESCRIPTION
**Pull request by inigomarquinez**
The objective of this PR is to have a `docs` folder under the root folder for all the files related to documentation.

Before it was under the `/tools` folder, which didn't make too much sense.

Apart from that, the `packages-in-scope.md` file has also been moved from `/tools/scope` to this new `/docs` folder.

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by UlisesGascon** [comment]
Additionally we will need to update:
- https://github.com/expressjs/express/blob/master/Security.md?plain=1#L51
- https://github.com/expressjs/security-wg/blob/main/README.md?plain=1#L10

**Review by carpasse — APPROVED** [review]

**Comment by inigomarquinez** [comment]
> Additionally we will need to update:
> 
> * https://github.com/expressjs/express/blob/master/Security.md?plain=1#L51
> * https://github.com/expressjs/security-wg/blob/main/README.md?plain=1#L10
> 
> As the reference have changed :)

@UlisesGascon do I create the PRs or do I wait until this PR is merged?

**Comment by UlisesGascon** [comment]
> do I create the PRs or do I wait until this PR is merged?

Feel free to create them, so we will merge queue them

**Comment by inigomarquinez** [comment]
@UlisesGascon 

I've already created a PR to update the reference to the Thread Model in the express documentation and I've modified this same PR to fix the location of the packages-in-scope.md file.

**Pull request merged**
